export const GET_KARTUPASIEN_DATAPASIEN = "GET_KARTUPASIEN_DATAPASIEN";
export const GET_KARTUPASIEN_BA = "GET_KARTUPASIEN_BA";
export const GET_KARTUPASIEN_DOKTER = "GET_KARTUPASIEN_DOKTER";
export const GET_KARTUPASIEN_PERAWATAN = "GET_KARTUPASIEN_PERAWATAN";
export const GET_KARTUPASIEN_LOKASIFOTOBEFORE =
  "GET_KARTUPASIEN_LOKASIFOTOBEFORE";
export const GET_KARTUPASIEN_LOKASIFOTOAFTER =
  "GET_KARTUPASIEN_LOKASIFOTOAFTER";
